name: Check Rebar Dependencies

on:
  pull_request:

jobs:
  check_deps_integrity:
    runs-on: ubuntu-22.04
    container: ghcr.io/emqx/emqx-builder/5.1-1:1.14.5-25.3.2-1-ubuntu22.04

    steps:
      - uses: actions/checkout@v3
      - name: Run check-deps-integrity.escript
        run: ./scripts/check-deps-integrity.escript
